version: "3.9"

services:
  app:
    build:
      context: .
      target: development
    container_name: user-scope-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
